### ISSUE TITLE
Github actions should test code built using intel compiler

### ISSUE THREAD

**Issue by JamieJQuinn** [Trovemaster/TROVE#31]
Currently github actions only compiles the code using gfortran and not with Intel's ifort. The binary from the compilers can differ substantially so the code would be best tested with both compilers. Although it's not entirely straightforward, Intel provides [sample CI configurations](https://github.com/oneapi-src/oneapi-ci) enabling fairly easy use of the intel toolchain in github actions. This should be implemented.

**Comment by ageorgou** [comment]
Done in #36.
